### ISSUE TITLE
Tower of Hanoi with Phoenix LiveView

### ISSUE THREAD

**Issue by wiserfirst** [elixirsydney/elixirsydney#10]
I managed to get the tower of Hanoi game I built during ElixirCamp work with drag-and-drop (Thanks for the help @joshprice) and this talk shares some of the learnings from this experience

**Comment by paulfioravanti** [comment]
Thanks for speaking, Qing! If you have any materials you wanted to share, like a link to your Tower of Hanoi repo or where it's deployed or your slide deck etc, then please tweet it out to `@ElixirSydney` and we'll give it a retweet.
