### ISSUE TITLE
Introduction to LiveView Components

### ISSUE THREAD

**Issue by paulfioravanti** [elixirsydney/elixirsydney#11]
As LiveView is all the rage at the moment, and as of LiveView 0.4.0, [LiveComponent](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html) was introduced to "to compartmentalize state, markup, and events in LiveView", so it would be great to get an introduction of LiveComponent, and what makes it different from a "standard" LiveView, when you would use it etc.

Links/Potential sources of inspiration:

- http://blog.pthompson.org/liveview-livecomponents-introduction
- http://blog.pthompson.org/phoenix-liveview-livecomponent-modal

**Comment by joshprice** [comment]
Going to close this one for now, as I touched on it in my lightning talk tonight.
