### ISSUE TITLE
My Journey to Elixir and Rate Limiting library

### ISSUE THREAD

**Issue by lenfree** [elixirsydney/elixirsydney#15]
I would love to share my journey with Elixir and show my interview solution writing a rate limiting library.

**Comment by paulfioravanti** [comment]
Thanks for submitting this presentation proposal, @lenfree!  Would you please be able to provide some more information so we can schedule you in?

- Brief summary of the talk content
- Which month's meetup you would like to present at (I'm assuming February?)
- Length of talk: full-length talk (max 30 minute) or lightning talk (~5 minutes)
- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by lenfree** [comment]
Hi @paulfioravanti , below is the summary:

* How I got started with Elixir
* Things I like and dislike
* Share my solution on rate limiter:
     * Problem: Only allow 100 request per minute based on ip address
     * Share my solution - demo, code &  technologies I used
     * Learnings

Please let me know if there's anything you'd like me to share.
   
I think this might be about 10 minutes talk? If we have a free slot for February, otherwise March is also good. With regards to Twitter handler, https://twitter.com/Potomptic and feel free to grab my Twitter profile photo.

**Comment by paulfioravanti** [comment]
Great, thanks very much @lenfree! We'll lock you in for February!

**Comment by paulfioravanti** [comment]
@lenfree do you have an actual photo of yourself that you wouldn't mind us using?

**Comment by paulfioravanti** [comment]
Thanks for your awesome talk, @lenfree, and thanks for [tweeting out your talk materials](https://twitter.com/Potomptic/status/1225162446551183360?s=20)!
