### ISSUE TITLE
Order Revealing Encryption for Cloud Data

### ISSUE THREAD

**Issue by coderdan** [elixirsydney/elixirsydney#16]
With significant data breaches becoming the daily norm, our approaches to storing data in the cloud, especially with 3rd party providers need to radically improve.

With the “holy grail” of Fully Homomorphic Encryption (FHE) still years away from practicality, Order Revealing Encryption (ORE) offers a compelling stepping stone to significant data security improvements.

In this talk, Dan will introduce both FHE and ORE, practical examples and how, in particular, ORE can allow for new security models for protecting data in the cloud.

**Comment by paulfioravanti** [comment]
Thanks, @coderdan! You're all locked in for Wednesday!

**Comment by paulfioravanti** [comment]
Thanks very much for the talk last night, @coderdan! If your slide deck is public, feel free to tweet a link to it out to `@ElixirSydney` and we'll re-tweet.
