### ISSUE TITLE
A small type-checked expression evaluator in Elixir

### ISSUE THREAD

**Issue by freshtonic** [elixirsydney/elixirsydney#18]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Brief summary of the talk content

In this talk I'll create a little language for evaluating simple boolean expressions, represented in AST form.

Imagine that these expressions come from user input to be used as filter criteria against a schema which is not knowable at app compile time. To avoid run time failures you'll need to type check the user supplied expression before running it - I will show you how to build a tiny type checker to prove there are no errors before running the code!

- Which month's meetup you would like to present at

March 2020

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)

20 - 30 mins.

- Your Twitter username (if you have one)

@freshtonic 

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by paulfioravanti** [comment]
Thanks @freshtonic! Locked in!

**Comment by paulfioravanti** [comment]
Thanks @freshtonic! If you end up putting your slides up somewhere, tweet them out to `@elixirsydney`!
