### ISSUE TITLE
The dream BEAM

### ISSUE THREAD

**Issue by jgmchan** [elixirsydney/elixirsydney#19]
Thanks for proposing a lightning talk for Elixir Sydney!

Please provide the following information:

- Name of talk (in the title field)
The dream BEAM

- Brief summary of the talk content
Why the BEAM is a DevOps Engineers dream deployment - plus short demo on Hot Deployments (maybe)

- Which month's meetup you would like to present at
March

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by paulfioravanti** [comment]
Thanks @jgmchan! Locked in!

**Comment by paulfioravanti** [comment]
Thanks @jgmchan! If you end up putting your slides up on the internet somewhere, tweet them out to `@elixirsydney`!
