### ISSUE TITLE
Exercism: matching brackets

### ISSUE THREAD

**Issue by suranyami** [elixirsydney/elixirsydney#20]
https://exercism.io/tracks/elixir/exercises/matching-brackets
Month: February 2020
![David Parry](https://user-images.githubusercontent.com/69984/75766860-e7e0c880-5d95-11ea-8a2f-ad4364891faf.png)

**Comment by paulfioravanti** [comment]
Yay! 🎉 Confirmed for tomorrow!

**Comment by paulfioravanti** [comment]
Thanks, @suranyami! If you've pushed your solution up to Exercism, tweet out the public link to your solution to `@elixirsydney` and we'll give it a re-tweet!
