### ISSUE TITLE
Real Time Strategy At Light Speed - Julian Doherty

### ISSUE THREAD

**Issue by madlep** [elixirsydney/elixirsydney#21]
Talk for the upcoming meeting on April 1.

30 min talk

twitter: [@madlep](https://twitter.com/madlep)

web: [juliandoherty.com](https://juliandoherty.com)

github / twitter profile pic is good to use: ![](https://avatars0.githubusercontent.com/u/27223?s=460&u=e9d1c4ecd22819d739b23287475321455dbccd93&v=4)

Abstract:
> Real time space battle multiplayer browser games are cool. But what if we want to play a real time space battle multiplayer game where the players are hundreds of millions of miles apart, and the speed of light is a factor in who sees what happening, and when?
>
> Hard sci-fi like "The Expanse", or "Dread Empire's Fall" go into excruciating detail on how long it takes to even see what is happening, and how long ago it really did happen - which could be minutes or hours. Battles play out like high latency, async chess games. Warships hurl missiles at each other over enormous distances and speeds, rather than frenetic "World War 2 fighter planes in space" you get in Star Wars.
>
> In a plain old Elixir realtime game, you don't have to worry about that - you just send all messages to all clients as soon as they arrive. But what if we need to delay some of those messages for an arbitrary amount of time depending on where different actors are in the virtual solar system? What design patterns and ways of thinking about how our app is built do we need to do to be able to build something like that?

**Comment by paulfioravanti** [comment]
Thanks for this evening, @madlep! When you get your slides up somewhere, please tweet them out to `@ElixirSydney` and we'll give them a re-tweet!
