### ISSUE TITLE
Event Sourcing with Commanded

### ISSUE THREAD

**Issue by fimac** [elixirsydney/elixirsydney#23]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Name of talk (in the title field) Event Sourcing with Commanded.
- Brief summary of the talk content - Sharing what I've learnt on Event Sourcing and implementing it with a library called Commanded.
- Which month's meetup you would like to present at - May.
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!) ~15-20mins
- Your Twitter username (if you have one) @saucerlike
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![FullSizeRender](https://user-images.githubusercontent.com/26052576/80566840-2f52a080-8a37-11ea-98fd-0f1e4afbb35c.jpg)

**Comment by paulfioravanti** [comment]
Thanks for doing your presentation, @fimac! I think you've got your slides up somewhere on the web, so please tweet out the link to `@ElixirSydney` and we'll retweet!
