### ISSUE TITLE
Randori mob programming exercise

### ISSUE THREAD

**Issue by madlep** [elixirsydney/elixirsydney#24]
- Name of talk (in the title field)
Randori mob programming exercise

- Brief summary of the talk content
We'll run a mob programming session using the [Randori](https://medium.com/connected/teaching-code-with-randori-51ac9a7fe7be) format. The basic concept is:
  - Pick a programming task. Something short, self contained, and with tests. Exercism problems are ideal.
  - 2 people working on the code at a time. One driver, one navigator. The Navigator thinks about the overall approach, the driver is "on the keyboard" and types and thinks about the line by line implementation
  - red/green TDD practiced
  - anyone in the audience can offer suggestions at any time, with some rules:
    - if tests are red, can only offer suggestions on how to get the tests passing
    - if tests are green, can offer suggestions on how to refactor the code
  - navigator/driver are swapped _at least every 5 minutes_. Everyone should get a turn.
    - if anyone is particularly vocal, or has ideas that require some explaining THEY become the navigator
    - the navigator becomes the driver
    - the driver goes back into the audience
  - everyone is encouraged to participate (or not participate if they are not comfortable). Ability/experience is not to be considered a blocker, as the entire group is coming up with the solution, not solely the navigator/driver
  - refactoring and exploring different implementations are encouraged. If someone has a totally different idea and wants to restructure everything, that is fine.
  - This can take some time, but if everyone is learning and enjoying it, that's fine.

I've run this as an in person event quite a few times at Elixir Melbourne, and it's very educational and a lot of fun. I'm thinking it _should_ be ok online, but we'll see. 

We'll try using https://repl.it/ - this way we can have a live, shared code editor and repl. However, **everyone who wants to participate will need to sign up for a free account, and login to get access to the realtime shared repl before the event**  (anon users can use repl.it, but not the realtime shared functionality)

- Which month's meetup you would like to present at:
May 2020

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!):
30 mins

- Your Twitter username (if you have one):
@madlep

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
github/twitter one is fine

**Comment by paulfioravanti** [comment]
Thanks @madlep! I think the mob programming went great! Definitely a great format to add to the meetup mix.

**Comment by paulfioravanti** [comment]
https://twitter.com/ElixirSydney/status/1263048033379291142

Just adding this for posterity's sake: the Exercism problem done for this meetup was [Secret Handshake](https://exercism.io/tracks/elixir/exercises/secret-handshake).
