### ISSUE TITLE
5 ways to solve the preload-top-n problem with Ecto 3.4

### ISSUE THREAD

**Issue by mbuhot** [elixirsydney/elixirsydney#25]
## Summary

Ecto associations are incredibly useful for working with relational data.
They simplify joins, inserts, and give an easy means to load related records with a query.

There's one problem that hasn't been well supported well until recently: `preload` the top N items from a `has_many` association.

In this talk I'll present 5 different ways to approach the problem with ecto, covering some recently added features including:

* subqueries
* named bindings
* lateral joins
* window functions
* common table expressions

---

- Which month's meetup you would like to present at: June (or July)
- Length of talk: 20 minutes
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: 
https://user-images.githubusercontent.com/336840/84208720-b7789b00-aaf7-11ea-8464-26a62b2bac65.png

**Comment by paulfioravanti** [comment]
Sounds like a great talk, @mbuhot! If you're good for June 17, we'd love to schedule you up! Do you have a Twitter account at all? If so, please let us know.

**Comment by mbuhot** [comment]
June 17 sounds great @paulfioravanti 👍 
I'm @MikeBuhot on twitter.

**Comment by paulfioravanti** [comment]
Awesome, thanks! You're all locked in!

**Comment by paulfioravanti** [comment]
Thanks very much for your talk tonight, @mbuhot ! If your slide deck is public somewhere, please tweet it out to `@ElixirSydney` and we'll give it a re-tweet!
