### ISSUE TITLE
Ecto.Multi: Composable transactions

### ISSUE THREAD

**Issue by edgurgel** [elixirsydney/elixirsydney#26]
`Ecto.Multi` provides a simple interface to compose database operations into a single transaction. 

I will present how `Ecto.Multi` works and how to write tests when using it. I also want to talk about what not to do with `Ecto.Multi`!

----

- Which month's meetup you would like to present at: June?
- Length of talk: 20 minutes
- Your Twitter username: edgurjas
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: https://avatars2.githubusercontent.com/u/30873?s=460&u=ab5398ec9a362983b555e702d3044fc752843bde&v=4

**Comment by paulfioravanti** [comment]
Awesome, thanks so much, @edgurgel! You're locked in for next Wednesday! Looks like we'll be having an Ecto Extravaganza!

**Comment by edgurgel** [comment]
Awesome! Thanks!

**Comment by paulfioravanti** [comment]
Thanks very much for your talk tonight, @edgurgel! If your slide deck is public, please tweet it out to `@ElixirSydney` and we'll give it a re-tweet!
