### ISSUE TITLE
Newton Slug Kilowatts

### ISSUE THREAD

**Issue by robinhilliard** [elixirsydney/elixirsydney#27]
### Newton Slug Kilowatts
It's easy to make mistakes with measurement units, especially when you're mixing imperial and metric. My (second) attempt to dealing with this problem is a 400ish line module that lets me write stuff like this:

```
iex> use Unit
iex> {1, :m} * {200, :cm}
{2.0, :m2}
iex> {61, :s} - {1, :min}
{1.0, :s}
iex> {9, :ft2} / {1, :m}
{0.8364312267657993, :m}
```

In the talk I'll cover: 
- Simple Elixir data structures that model relationships between units (inches, cm, feet are all lengths) and dimensions (length, area, time, acceleration, power, ...)
- A technique for handling distinct error cases in `with` statements and 
- Show how straight forward it is to extend the built in arithmetic operators in Elixir.
 
Suggested 30 minute July 2020 talk
@robinhilliard 
robin@rocketboots.com
![Robin](https://user-images.githubusercontent.com/788490/84607302-dc05b600-aeef-11ea-9b73-ac70f9ef68db.png)

**Comment by paulfioravanti** [comment]
Thanks so much, @robinhilliard! You're locked in for July!

**Comment by paulfioravanti** [comment]
Thanks for the presentation tonight, @robinhilliard! If you make the slide deck public, please tweet it out to `@elixirsydney`/`@ElixirMelbourne` and we'll retweet it!
