### ISSUE TITLE
Strong, static FP on the BEAM with Hamler

### ISSUE THREAD

**Issue by freshtonic** [elixirsydney/elixirsydney#28]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Strong, static FP on the BEAM with Hamler
- Will do an intro to strongly-typed functional programming without going too deep (wil gloss over monads!)
- August
- 30 mins, but may need to do a part 2 another time. There's a lot to cover.
- @freshtonic
- You already have a photo :)

**Comment by paulfioravanti** [comment]
Leaving it up to me to decide your photo? I see you like to live dangerously 😉 Consider yourself scheduled!

**Comment by paulfioravanti** [comment]
@freshtonic booked for September 2020!
