### ISSUE TITLE
Massively Multiplayer Clicking With Phoenix LiveView

### ISSUE THREAD

**Issue by madlep** [elixirsydney/elixirsydney#29]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Massively Multiplayer Clicking With Phoenix LiveView
- Code walk through of how to put together a simple real time multiplayer clicker game with LiveView. This is an extended version of a lightning talk on LiveView I did at work at Envato. The app is online for people to see running at https://bossclick.madlep.com/ , and is kinda fun to get everyone to spam clicks into it at the start. Code is at https://github.com/madlep/boss_click
- July 2020
- 30 mins, or shorter. Was a lightning talk originally, and can flex length to fit.
- @madlep
- ![image](https://user-images.githubusercontent.com/27223/87488233-2e6afb80-c683-11ea-812c-4dafa7eed541.png)

**Comment by paulfioravanti** [comment]
Thanks for the last minute addition, @madlep!
