### ISSUE TITLE
Armstrong Numbers Exercise

### ISSUE THREAD

**Issue by Rhiana** [elixirsydney/elixirsydney#30]
Going through the [exercism Armstrong numbers exercise](https://exercism.io/my/tracks/elixir#exercise-armstrong-numbers) as an Elixir beginner

- Which month's meetup you would like to present at
Can present next month in August

![Rhiana](https://user-images.githubusercontent.com/5127756/87616771-37c69780-c759-11ea-800d-ea322cc56310.jpg)

**Comment by paulfioravanti** [comment]
Thanks so much, @Rhiana! You're all locked in for August!

**Comment by paulfioravanti** [comment]
Hi @Rhiana, just a ping to double check you're still all good for Wednesday?

**Comment by Rhiana** [comment]
Yep no worries @paulfioravanti, see you then

**Comment by paulfioravanti** [comment]
Thanks for your talk last week, Rihana! If you had any materials from the talk that you share online, please tweet out to `@elixirsydney` and we'll give them a re-tweet!
