### ISSUE TITLE
Cipherstash: A fully encrypted search index written in Elixir and gRPC

### ISSUE THREAD

**Issue by coderdan** [elixirsydney/elixirsydney#33]
I've been working on a new kind of database written in Elixir and C: its fully encrypted with client-side keys and supports full text search. And it has an Ecto adapter!

I'd love to share the tool as well as some of the lessons learned working with gRPC and HTTP2 in Elixir as well as how to craft a custom Ecto adapter.

Twitter username: @danieldraper.
Happy for you to use my avatar from twitter.

**Comment by paulfioravanti** [comment]
Awesome, @coderdan! Consider yourself scheduled up for September!
