### ISSUE TITLE
Supervisors and upgrading an Elixir Application

### ISSUE THREAD

**Issue by keithpitty** [elixirsydney/elixirsydney#34]
## Summary

The inimitable folks who run the Sydney Elixir meetup have enticed me to share a few things based on a tweet I posted:

> Time to deepen my understanding of supervisors, workers and genservers in conjunction with using Erlang's observer. #myelixirstatus

OK!

## Month

October 2020 or later

## Mugshot

https://keithpitty.com/packs/media/images/keith-ce308afabf545afd4bfc4f252bbf93b4.jpg

**Comment by paulfioravanti** [comment]
Brilliant, @keithpitty! Thank you! Let's book you in for October, and confirm again closer to the date!

**Comment by keithpitty** [comment]
@paulfioravanti when's the next meetup?

**Comment by paulfioravanti** [comment]
@keithpitty October 21. Want to do your talk then?

**Comment by keithpitty** [comment]
@paulfioravanti probably best to leave it until November. I have a bit too much on my plate this month.

**Comment by paulfioravanti** [comment]
@keithpitty No problems at all, and thanks for letting me know. Shall we re-confirm your status in November, or shall I just go directly and schedule you up for November?

**Comment by keithpitty** [comment]
@paulfioravanti I'm happy for you to lock me in for November. Would that be on the 18th?

**Comment by paulfioravanti** [comment]
@keithpitty Yep, on the 18th. I just removed the stale event from the old schedule (sorry for the confusion). I'll go ahead and lock you in for November.

**Comment by keithpitty** [comment]
@paulfioravanti apologies but I'm going to need to retract my commitment to speak in November. My circumstances have changed such that I need to step back from extra commitments such as speaking at meetups for the time being.

**Comment by paulfioravanti** [comment]
@keithpitty no problem at all. Hope everything is okay. I'll remove the milestone, but feel free to either keep this issue open in hopes that it will happen at some point or close it.

**Comment by paulfioravanti** [comment]
@keithpitty just pinging this issue to see what your appetite is these days about speaking.

**Comment by keithpitty** [comment]
@paulfioravanti thanks for prompting me. Probably best to scrap this. Apologies for the inconvenience.
