### ISSUE TITLE
ISBN Verifier Verily Verified

### ISSUE THREAD

**Issue by robinhilliard** [elixirsydney/elixirsydney#35]
I know the Exercism lighting talks are supposed to be an opportunity for new speakers, but I sort of accidentally did the ISBN one and a few others. Out of interest I've also just written the ISBN one in LFE. Both versions are 9 lines long so should fit into a lightning talk. Unfortunately I'm not free September 16, someone else can present them if they'd like, otherwise will try for October.

### Elixir
```
defmodule IsbnVerifier do

  @spec isbn?(String.t()) :: boolean
  def isbn?(isbn), do: isbn?(isbn, 10, 0)
  def isbn?(<<c, rest::binary>>, n, sum) when c in ?0 .. ?9, do: isbn?(rest, n - 1, sum + n * (c - ?0))
  def isbn?(<<?-, rest::binary>>, n, sum), do: isbn?(rest, n, sum)
  def isbn?("X", 1, sum), do: isbn?(<<>>, 0, sum + 10)
  def isbn?(<<>>, 0, sum), do: rem(sum, 11) == 0
  def isbn?(_, _, _), do: false
  
end
```

### LFE
```
(defmodule isbn-verifier (export (isbn? 1)))

(defun isbn? (isbn) (isbn_verify isbn 10 0))

(defun isbn_verify
  (((cons c rest) n sum) (when (and (>= c #\0) (=< c #\9))) (isbn_verify rest (- n 1) (+ sum (* n (- c #\0)))))
  (((cons #\- rest) n sum) (isbn_verify rest n sum))
  (("X" 1 sum) (isbn_verify '() 0 (+ sum 10)))
  (('() 0 sum) (== 0 (rem sum 11)))
  ((_ _ _) 'false)
)
```

**Comment by paulfioravanti** [comment]
Thanks for this, @robinhilliard! It's unfortunate that you won't be able to make it to September's meetup, but how about we do this:

- If someone steps up to either show their own solution to the Exercism problem (or present yours if they want) this month, then they can have the slot
- If no one steps up, then you can present your solution and Elixir/Erlang compare/contrast at the October 2020 meetup

**Comment by robinhilliard** [comment]
Sure. I'd actually gone to some lengths to not have a clash with the Elixir UG but it turned out that way. If someone else does it maybe mention that I put up a solution here people can check out.

**Comment by paulfioravanti** [comment]
Doesn't seem that anyone has come forward, so would you be okay to be scheduled up for this month, @robinhilliard ?

**Comment by robinhilliard** [comment]
For the lightening talk? Sure. If you need a slightly longer talk I can also show the BEAM assembler code for the exercise, it's quite interesting to see the raw stuff run by the VM for a simple program like this one.

**Comment by paulfioravanti** [comment]
Taking deep diving on an Exercism exercise to the next level with some BEAM assembler code sounds like a great idea! If you're happy with it, I'm more than happy to convert this from a lightning talk to full length.

**Comment by robinhilliard** [comment]
Ok can do. Just so you know BEAM assembler is only partially documented at this point so all I can do is generate and walk/talk through the .S file and maybe compare the Elixir and LFE output (should be very similar).

Talk Description

**ISBN Verifier Verily Verified**
Let's do a nice compact answer to the Excercism ISBN Verifier challenge. Then for those of you curious about other loosely typed LISP-like languages (e.g. Clojure) we'll rewrite it in Robert Virding's LFE (LISP Flavoured Erlang). After the rioting subsides we will close with a reminder that we're all part of one big happy BEAM family by looking at the surprisingly understandable BEAM VM assembly code generated by the Elixir/LFE/Erlang build chain.

**Comment by robinhilliard** [comment]
Speaker Bio: 

Robin Hilliard, the only other person Joe Biden has ever said "Will you shut up, man?" to is a regular speaker at Elixir Sydney. In an Elixir Sydney first this talk is genuinely not in any way related to aviation or drones.

**Comment by paulfioravanti** [comment]
Awesome, you're all scheduled up!

**Comment by robinhilliard** [comment]
The speaker link on the meetup page https://github.com/elixirsydney/elixirsydney/issues gets a 404 - are we going to update the meetup page with the description/bio? :-)

**Comment by paulfioravanti** [comment]
Accursed full-stops! Fixed now. I'll update the meetup page this evening with all the info :+1:

**Comment by robinhilliard** [comment]
Presentation slide links in [Keynote]( https://www.dropbox.com/s/kloe11pzn0hvmvx/ISBNVerifier.key?dl=0)  and [PDF](https://www.dropbox.com/s/r03tpzeyfbuc8h4/ISBNVerifier.pdf?dl=0) format.

**Comment by paulfioravanti** [comment]
Thanks for your talk yesterday, @robinhilliard! Feel free to tweet out the presentation links as well and we'll re-tweet. I'll also tweet out when the videos are up.
