### ISSUE TITLE
Pros, Cons, and Quick wins with Elixir escripts

### ISSUE THREAD

**Issue by mendokusai** [elixirsydney/elixirsydney#36]
- Brief summary of the talk content

Working on some electronics, I needed a resistor calculator and I wanted to bootstrap a command line tool for quick use - disliking to mouse through website forms. I decided to use an escript to make a command-line executable, quickly. It was easy and did the job in the ecosystem I wanted. Got it done, quickly.

After the fact, I realized that escripts weren't without their issues, so really, this talk is a way to spend a bit of time to learn some of those edges and share the experience, the pros, and the cons of Elixir escripts.

- Which month's meetup you would like to present at
October

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
~15min

- Your Twitter username (if you have one)
@ryapauley

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
https://try.sendle.com/hubfs/Sendle_December_2017/Image/ryan-d2c06eb0f5b2c2ef1debe416990f6ed5.jpg

**Comment by paulfioravanti** [comment]
Awesome, thanks, @mendokusai ! You're locked in for October!

**Comment by mendokusai** [comment]
Here's my Resistor Calculator Repo if anyone wanted to [checkout escript the setup](https://github.com/mendokusai/resistor_calc)

**Comment by paulfioravanti** [comment]
Thanks so much for your talk yesterday, @mendokusai! :D If you want to tweet out the link you posted in the previous comment and/or a link to your slides, please do and we'll re-tweet. Will also tweet out once the videos are up.
