### ISSUE TITLE
Haskell As Elixir

### ISSUE THREAD

**Issue by madlep** [elixirsydney/elixirsydney#37]
- Haskell As Elixir
- Haskell has a rich type system with elegant and sophisticated ways of defining and working with data structures. Elixir has awesome things we all know and love, but less of that. How can we abuse macros and Elixir type specs to build a DSL that sort of gives us some of the same conciseness and elegance?
- Nov 2020 or whenever
- 30 mins, but flexible
- @madlep on Twitter and GitHub / https://juliandoherty.com
- Twitter/GitHub pic is good

**Comment by paulfioravanti** [comment]
Locked in for next week! Thanks, @madlep!

**Comment by paulfioravanti** [comment]
@madlep just confirming you're still okay for this talk to have been moved to this month?

**Comment by madlep** [comment]
@paulfioravanti . Yup. All good for this month 👍

**Comment by paulfioravanti** [comment]
Thanks, Julian!

Video: https://www.youtube.com/watch?v=g5NDSLCLwFw

If you end up putting your slides up somewhere, tweet them out and we'll re-tweet!
