### ISSUE TITLE
gRPC in Elixir

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#38]
- gRPC is "A high-performance, open source universal RPC framework" and is an option for inter-service communication along with ReST and GraphQL and is also a contender for the "last mile" communications to devices and browsers.  This talk will cover what gRPC is, and demo the most popular gRPC library for Elixir (https://github.com/elixir-grpc/grpc), showing how Elixir can communicate with services written in other languages we're likely to need to interoperate with in the current software landscape.
- November 2020
- 30 mins
- @robertellen (twitter)

**Comment by paulfioravanti** [comment]
Champion! Thanks, @rellen! You're scheduled in for next week!

**Comment by paulfioravanti** [comment]
If you end up putting your slide deck online somewhere (Slideshare, Speakerdeck etc), please tweet it out and we'll give it a re-tweet.
