### ISSUE TITLE
Bitwise fun with Elixir

### ISSUE THREAD

**Issue by wiserfirst** [elixirsydney/elixirsydney#40]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Bitwise fun with Elixir
- For most web developers, bitwise operations are not very familiar, but in some situations they can be quite useful and they are by nature super performant. In this talk, I'll try to lead the audience to have some fun with bitwise operations in Elixir.
- Aiming for Dec 2020 if I could get it ready by then
- around 15 minutes
- @wiserfirst for Twitter and Github
- Github profile picture is good

**Comment by paulfioravanti** [comment]
Locked in for December!

**Comment by paulfioravanti** [comment]
Thanks, Qing!

Video: https://www.youtube.com/watch?v=X8QfT7BNE44

If you end up sharing you slides somewhere, like Speakerdeck etc, tweet out a link and we'll re-tweet!
