### ISSUE TITLE
Safe-ish: A BEAM-bytecode-level-load-time-sandboxy-library-thing

### ISSUE THREAD

**Issue by robinhilliard** [elixirsydney/elixirsydney#42]
Safe-ish is an experimental sandbox for BEAM modules that examines and rejects BEAM bytecode containing instructions that could cause side effects. You can provide an optional whitelist of opcodes and functions the module can use.

https://hex.pm/packages/safeish

In this talk Robin will talk about his summer holiday project, or what happens when you put a series of 100 USD bounties to break your library up on the Elixir language forums. It also talks about the beam file format and  writing a rudimentary BEAM file disassembler in Elixir using binary pattern matching.

Use previous bio and picture - February perhaps?

**Comment by paulfioravanti** [comment]
Thanks, @robinhilliard ! Looks like you've been busy over the break! Happy to schedule you up for February :+1:

**Comment by robinhilliard** [comment]
PDF of presentation slides:

[Safeish.pdf](https://github.com/elixirsydney/elixirsydney/files/5988123/Safeish.pdf)

**Comment by paulfioravanti** [comment]
Thanks, @robinhilliard. Tweet this link out after your talk as well and `@elixirsydney` will re-tweet.

**Comment by robinhilliard** [comment]
Final slides with presenter notes [Safeish_Elixir_Sydney_Feb_21.pdf](https://github.com/elixirsydney/elixirsydney/files/5993127/Safeish_Elixir_Sydney_Feb_21.pdf)

**Comment by robinhilliard** [comment]
Final final slides with presenter notes [Uploading Safeish_Elixir_Sydney_Feb_21.pdf…]()

**Comment by robinhilliard** [comment]
Final final final slides including Bram's actual Bounty 1 source code
[Safeish_Elixir_Sydney_Feb_21.pdf](https://github.com/elixirsydney/elixirsydney/files/5994837/Safeish_Elixir_Sydney_Feb_21.pdf)

**Comment by paulfioravanti** [comment]
Thanks for your talk, @robinhilliard!
