### ISSUE TITLE
Sensors, Beers and Nerves

### ISSUE THREAD

**Issue by fimac** [elixirsydney/elixirsydney#45]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content:- After recently getting into brewing beer and wanting to learn more about programming hardware and sensors, this talk is about a small project in setting up a Bosch BME280 temperature sensor using Nerves and a Raspberry Pi Zero W, and monitoring and displaying the data.
- Which month's meetup you would like to present at: February or March.
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!) 20-25 mins
- Your Twitter username (if you have one) @saucerlike
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
![fiona](https://user-images.githubusercontent.com/26052576/107184195-3da50280-6a34-11eb-87d4-b6212acd7ace.jpg)

**Comment by paulfioravanti** [comment]
Awesome, @fimac! 🎉 If you can be ready for next week, I'm more than happy to lock you in!

**Comment by fimac** [comment]
Yep, I can be ready for next week. Lock me in @paulfioravanti 👍

**Comment by paulfioravanti** [comment]
Thanks for your great presentation, @fimac! If you end up making your slide deck public, tweet a link to them out and we'll re-tweet :)
