### ISSUE TITLE
Kicking the tyres on Nx (Numerical Elixir)

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#46]
- Nx: numerical Elixir is a project with the aim of bringing high performance numeric computations to Elixir.  
  - What is it
  - What has it/ can it be used for
  - Demo
- Timeframe: Once enough detail/code has been released to make stuff in Nx, perhaps as early as March
- Length of talk: 20-30mins

**Comment by paulfioravanti** [comment]
Thanks, @rellen! When you're ready to confirm a spot you want, please update this issue and we can schedule you up.

**Comment by paulfioravanti** [comment]
Locking this talk in for March meetup 🎉

**Comment by paulfioravanti** [comment]
Thanks very much, @rellen! If you put your presentation materials up on the interwebs somewhere, feel free to tweet it out and we'll get the Elixir Sydney account to re-tweet.
