### ISSUE TITLE
pig latin exercism walk through

### ISSUE THREAD

**Issue by madlep** [elixirsydney/elixirsydney#47]
Thanks for proposing a lightning talk for Elixir Sydney!

Please provide the following information:

- Pig Latin Exercism walk through
- Solving [pig latin exercise](https://exercism.io/my/solutions/dd9df9bf8f6d46b2a9027731b0d83c98). Let's have a look at how we can do the whole thing using pattern matching.
- March 2021
- photo from github / twitter fine

**Comment by paulfioravanti** [comment]
Lifesaver, @madlep ! You're locked in for tomorrow!

**Comment by paulfioravanti** [comment]
Thanks, @madlep! Feel free to tweet out the link to your solution when you put it up on Exercism and we'll retweet it out.
