### ISSUE TITLE
Talk proposal: Phoenix Contexts asymmetry

### ISSUE THREAD

**Issue by lessless** [elixirsydney/elixirsydney#48]
- Name of talk: Phoenix Contexts asymmetry
- Brief summary of the talk content: Phoenix Contexts were introduced 4 years ago with the intention to help us to step out of the basic set of entities offered by the MVC pattern. Yet they still cause confusion to the beginners and experienced developers alike. In this brief presentation, we will look into the rationale for introducing Contexts, the most spread pitfall when using them, and will try to build an overall understanding of how to avoid it.
- Which month's meetup you would like to present at: 21st of April
- Length of talk: 20-22 minutes
- Your Twitter username: @lessless_ua
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

**Comment by lessless** [comment]
Thanks, Paul! This topic is among long-standing interests of mine and I truly miss community events.
Hope we will have a blast 🙌 !

**Comment by joshprice** [comment]
I have added this to the meetup page. @lessless can you please confirm that you're all set for tomorrow night?

**Comment by lessless** [comment]
@joshprice still polishing, otherwise yes :)

**Comment by paulfioravanti** [comment]
Thanks, @lessless! Keep an eye out on the `@elixirsydney` Twitter account for an announcement of when your video gets published to our YouTube channel, and if you end up sharing your slide deck publicly, please tweet it out to `@elixirsydney` and we'll make sure to re-tweet it!

**Comment by lessless** [comment]
I have mixed feelings about the recording... but as the saying goes - when you start to speak a foreign language it's not your problem anymore ;)

I'll review slides and upload them asap! 

Great hangout guys! I had to bounce off to get back to my normal working day but can imagine how it could go further over the couple of drinks!

**Comment by paulfioravanti** [comment]
Hey @lessless, I just wanted to address your comment quickly:

> I have mixed feelings about the recording...

Personally, I really enjoyed your talk and thought you did a great job!

However, if you're not happy with how the talk turned out, for whatever reason, I am prepared to take it down from the Elixir Australia YouTube channel. Having you happy with the end result is the most important thing to us, so if that is not the case, please don't hesitate to let me know, either in this thread, or via direct message.

**Comment by lessless** [comment]
thanks, @paulfioravanti,

let it be - it's much better than the first stab that I took on that topic a few years ago hehe :)

**Comment by lessless** [comment]
I'll then think about another topic to share - lessons learned from using mocks.
