### ISSUE TITLE
OTP24 and Elixir 1.12 Release bonanza!

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#49]
- Synopsis: Go through the major changes in OTP24 and Elixir 1.12, including but not limited to:
  - AsmJit
  - EEP 54 (better error messages)
  - Mix.install
  - Kernel.then and Kernel.tap
  - stepped ranges
  - Enum.zip_with et al
  - and so much more!
- May - ideally 1.12 will be out but it's fine if it's not
- 15-20 minutes - (could be done as an extended news item)
- @robertellen

**Comment by paulfioravanti** [comment]
Locked in!

**Comment by paulfioravanti** [comment]
Thanks, @rellen! Uploaded to the YouTubes: https://www.youtube.com/watch?v=ucgYT3YUVS8
