### ISSUE TITLE
Elixir for UAV Avionics

### ISSUE THREAD

**Issue by robinhilliard** [elixirsydney/elixirsydney#50]
Direct from YOW LambdaJam 21!

Fault tolerant, concurrent, distributed and functional with superior binary wrangling capabilities and network/device connectivity - the Erlang platform designed to run the world's telephony systems also turns out to be a perfect fit for autonomous aerial vehicle control software.

In this presentation Robin will give a brief introduction to  the world of autonomous aircraft, autopilots, onboard companion computers, ground stations and communication links. He will demonstrate the use of his open source Elixir MAVLink library to communicate with an Ardupilot autopilot from Elixir code, which in turn will control an  accurate X-Plane simulation of a large UAV he has been working with since 2014.

Robin is the Founder & Chief Technology Officer of RocketBoots, a company providing hybrid SaaS-Edge computer vision products for major banks and retailers in Australia and New Zealand. With a life long interest in aviation and aeronautical engineering Robin is a private pilot and has been dabbling with UAV software and hardware development since 2014, including multiple attempts to qualify for the UAV Outback Challenge competition. He has tried to talk about non-aviation topics at Elixir Sydney but has basically given up. Stil, more than one person who isn't Robin has said this talk is ok:

> "Fantastic thanks @RobinHilliard (clap)"

Tim McGilchrist

> "That was excellent, thank you"

Jono

> "Damn, this is a super awesome talk (We’re watching it 20 mins delayed, no one ruin the ending for @LukeWorth (Bellroy)and I!). I need to get back into this world. Thanks @RobinHilliard"

Alex Mason

> "Amazing! Just finished watching it. I wouldn't change anything! All that context is important and interesting. Fair play if you want to extend the demo"

Paul Fioravanti

May 21

Talk 30 minutes, demo 10-15 minutes

@robinhilliard
Same pic as previous

**Comment by paulfioravanti** [comment]
Thanks, @robinhilliard ! Locked in!

**Comment by paulfioravanti** [comment]
Thanks, @robinhilliard! Here is the YouTube link to your talk: https://www.youtube.com/watch?v=k42wySIAbv0
