### ISSUE TITLE
Journey of adopting Elixir

### ISSUE THREAD

**Issue by gzzengwei** [elixirsydney/elixirsydney#51]
- Journey of adopting Elixir
- How the company start using Elixir for internal/small services on the k8s stack
- July 2021
- Length of talk (20~ minutes)
- Twitter (@gzzengwei)
- photo from twitter

**Comment by paulfioravanti** [comment]
Thanks for the submission, @gzzengwei, and that talk sounds great! Please consider yourself locked in for July!

**Comment by paulfioravanti** [comment]
Thanks very much, @gzzengwei! Video of your talk is up on our channel! https://www.youtube.com/watch?v=jsuq489JwzI
