### ISSUE TITLE
Rotational Cipher with Elixir

### ISSUE THREAD

**Issue by phonnz** [elixirsydney/elixirsydney#52]
- Solution proposal of Exercism Elixir Track - Rotational Cipher
- July 21
- https://phonnz.dev/img/phonnz.jpg

**Comment by paulfioravanti** [comment]
Hey Alfonso, thanks very much for your submission! You're locked in for July 21!

**Comment by paulfioravanti** [comment]
Thanks very much @phonnz! Video of your talk is up on our channel: https://www.youtube.com/watch?v=DP1OXKbq33Y
