### ISSUE TITLE
Porting procedural code to Elixir - what could go wrong?

### ISSUE THREAD

**Issue by mbuhot** [elixirsydney/elixirsydney#53]
I'll share the experience of solving the 'Goonerism Spenerator' puzzle in typescript, and porting the resulting code to elixir. 
What comes next will shock you 😱

**Comment by paulfioravanti** [comment]
Locked in for 🥄 action in August 18!

**Comment by paulfioravanti** [comment]
Thanks, @mbuhot! Video will be up on the YouTube channel soon enough!
