### ISSUE TITLE
Getting up and running with PromEx

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#54]
- PromEx (https://github.com/akoutmos/prom_ex) is a fantastic library that turns BEAM telemetry events into metrics that can be scraped by the Prometheus timeseries monitoring system.  It also has the added feature of providing some in-built Grafana charts that can be uploaded directly to a Grafana instance.  In this talk we will walk through setting up a local PromEx environment including Prometheus and Grafana with Docker to show how quickly you can get some metrics going in your Elixir applications.
- September 2021
- Length of talk 20 mins
- @robertellen

**Comment by paulfioravanti** [comment]
Locked in!

**Comment by paulfioravanti** [comment]
Thanks, @rellen! Talk now up on the YouTubes! https://www.youtube.com/watch?v=bLdheYG7BwQ
