### ISSUE TITLE
Journey of Upgrading an App to Phoenix 1.6

### ISSUE THREAD

**Issue by wiserfirst** [elixirsydney/elixirsydney#55]
- Brief summary of the talk content: Phoenix 1.6 RC0 was released just two weeks ago and I'm very excited about it.
Over the weekend, I managed to upgrade my little side project to Phoenix 1.6. In this talk I'll share my journey.

- Which month's meetup: September
- Length of talk: 15-20 min
- Your Twitter username: @wiserfirst
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: Github profile picture is fine.

**Comment by paulfioravanti** [comment]
Thanks, @wiserfirst! Your talk is now up on YouTube! https://www.youtube.com/watch?v=NR_Jk3yUEqc
