### ISSUE TITLE
Elixir way from a project revisiting 

### ISSUE THREAD

**Issue by gzzengwei** [elixirsydney/elixirsydney#57]
- Title: Elixir way from a project revisiting 
- Brief summary: while revisiting one of my earlier elixir project, I found it might be a good introduction of elixir approach (Task/GenServer/GenStage) for beginners
- Which month's meetup you would like to present at: Nov 2021
- Length of talk: 15 mins
- Twitter: gzzengwei
- twitter photo

**Comment by paulfioravanti** [comment]
Thanks, @gzzengwei! You're on for Wednesday!

**Comment by paulfioravanti** [comment]
Thanks very much, @gzzengwei! Your video is now up on the Elixir Australia YouTube channel!

https://www.youtube.com/watch?v=RFvuAN3AVHo

**Comment by gzzengwei** [comment]
- talk slide repo: [https://github.com/gzzengwei/presentation/tree/master/elixir-way-revisit](https://github.com/gzzengwei/presentation/tree/master/elixir-way-revisit)

- demo code: [https://github.com/gzzengwei/elixir-way-revisit-job-demo](https://github.com/gzzengwei/elixir-way-revisit-job-demo)

**Comment by paulfioravanti** [comment]
Tweet these out from your account and tag `@ElixirSydney` and we'll retweet!
