### ISSUE TITLE
ALF - Flow-based Application Layer Framework

### ISSUE THREAD

**Issue by antonmi** [elixirsydney/elixirsydney#58]
Hey colleagues!
I've returned to work on Flow-based programming in Elixir recently.
My new project is very ambitiously called ALF - Application Layer Framework.
The core functionality is ready and I’m gradually promoting it. 

Please check it here 
https://github.com/antonmi/ALF
There is also an introductory article in Medium
[ALF — Flow-based Application Layer Framework | by Anton Mishchuk | Dec, 2021 | Medium 21](https://anton-mishchuk.medium.com/alf-flow-based-application-layer-framework-8072ae9b0b6b)

I would like to make a presentation and hear true-engineering feedback!

**Comment by paulfioravanti** [comment]
Sounds fascinating, @antonmi! Would definitely love to have you present! Would you be ready for the [December 15 Meetup at 7pm AEDT](https://www.meetup.com/elixir-sydney/events/gztkjsyccqbtb/)?

**Comment by antonmi** [comment]
Hey Paul! Nice!
Yeap, I'll prepare ~30 min talk!
What's the best way to communicate with you? I've tried Meetup message, but no way.

**Comment by paulfioravanti** [comment]
Yeah, meetup messaging isn't great. Well, you can either feel free to communicate via this issue, or email me at paul.fioravanti@gmail.com or tweet me at `@paulfioravanti`.

**Comment by paulfioravanti** [comment]
Thanks again for the talk, @antonmi! Here's [a tweet to your video](https://twitter.com/ElixirSydney/status/1471419688240357378?s=20)!

**Comment by antonmi** [comment]
Thanks, Paul!
