### ISSUE TITLE
Macro Madness: when busting boilerplate backfires

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#60]
- Brief summary of the talk content:  
   A brief talk about an adventure in writing some macro code to reduce boiler-plate (will update summary to be more descriptive)
- Month: Feb
- Length: 15mins
- @robertellen

**Comment by paulfioravanti** [comment]
You're on for Wednesday, @rellen!

**Comment by paulfioravanti** [comment]
Thanks for blowing our collective minds, @rellen! :D
