### ISSUE TITLE
Wordle, Elixir flavour

### ISSUE THREAD

**Issue by Theosaurus-Rex** [elixirsydney/elixirsydney#61]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

**- Name of talk (in the title field)**
- Wordle, Elixir flavor

**- Brief summary of the talk content**
As a "simple" starter project while learning Elixir, we decided to rebuild Wordle using a combination of Elixir, Phoenix Liveview, and TailwindCSS. This is a showcase of the lessons learned, the overall process, and some of the tricky bits that popped up along the way. Of course, we'll also play a game of Wordle, so get your dictionaries ready!

**- Which month's meetup you would like to present at**
March 2022

**- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)**
Around 15-20min 

**- Your Twitter username (if you have one)**
@dino_coder 

**- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)**
My GitHub pic is fine!

**Comment by aplazarevska** [comment]
You can use my GitHub pic as well. I don't use Twitter.

**Comment by paulfioravanti** [comment]
Aaand, your video is [live](https://www.youtube.com/watch?v=OIOlNr7LRz4)! Thanks to you both for the presentation!
