### ISSUE TITLE
Exhelp: A Command Line Elixir Helper Show & Tell

### ISSUE THREAD

**Issue by rowlandcodes** [elixirsydney/elixirsydney#62]
If you're unable to find anyone to speak tomorrow (May meetup),
I can give an impromptu show & tell on Exhelp:
https://github.com/rowlandcodes/exhelp

# Summary
Exhelp is a tool that brings IEx's helpers to the command line.
My presentation would be an informal show & tell of the tool,
Along with some of the discoveries I made while digging through the internals of IEx,
Or dealing with the limitations of escripts.

## Length
As long as people have questions or curiosity.

## Social Media
https://row.land

## Photo
https://row.land/images/Rowland-2020-05-25-full.jpg

If you would prefer not to field an impromptu talk,
I understand, choose elsewhere.

**Comment by paulfioravanti** [comment]
Sold! You're on for tomorrow, @rowlandcodes!

**Comment by paulfioravanti** [comment]
Thanks very much, @rowlandcodes! Will let you know when the video goes up!

**Comment by paulfioravanti** [comment]
Video link is [here](https://www.youtube.com/watch?v=yyG_YeP5OTk).
