### ISSUE TITLE
Testing LiveViews - A Beginner's Guide

### ISSUE THREAD

**Issue by Theosaurus-Rex** [elixirsydney/elixirsydney#63]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

- Name of talk (in the title field)
- Brief summary of the talk content
- Which month's meetup you would like to present at
- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
- Your Twitter username (if you have one)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

## Summary
As someone relatively new to the world of LiveView, testing highly interactive applications has been somewhat of an enigma. This talk will give a broad overview of just how simple it can be to use the LiveViewTest module for writing a range of different tests, as well as tips for avoiding brittle or flaky tests.

## Month
Either June or July 2022 would be good :)

## Length
Around 20 minutes (est.)

## Twitter
Find me as [@dino_coder](https://twitter.com/dino_coder)

## Speaker Pic
<img src="https://user-images.githubusercontent.com/71990001/169418711-b82d727b-1050-41b6-8845-e571c9235334.jpg" width="250" />

**Comment by paulfioravanti** [comment]
Thanks, @Theosaurus-Rex! Booked for June 2022!
