### ISSUE TITLE
Ten years of Elixir!  And OTP/Elixir release bonanza! 2022 edition

### ISSUE THREAD

**Issue by rellen** [elixirsydney/elixirsydney#64]
- Brief summary of the talk content: Let's celebrate Elixir's 10th anniversary. Robert will facilitate an interactive session where we share some stories about our Elixir journeys.  Then a Livebook going over the latest in OTP and Elixir releases.
- 30mins max
- June

**Comment by paulfioravanti** [comment]
Thanks, Rob, you're on!
