### ISSUE TITLE
Building a HEEX components library

### ISSUE THREAD

**Issue by mplatts** [elixirsydney/elixirsydney#65]
Thanks for proposing a talk for Elixir Sydney!

Please provide the following information:

### Brief summary of the talk content

- History of components in Phoenix
- HEEX vs Surface
- How to build a HEEX component
- How to manage a component library for your project
- Petal Components as an example library

### Which month's meetup you would like to present at
Aug

### Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
30mins

### Your Twitter username (if you have one)
mplatts

### Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)

https://res.cloudinary.com/wickedsites/image/upload/v1656902939/f6crqjv7wsxdlp5y6odm.jpg

**Comment by paulfioravanti** [comment]
Hi Matt, thanks very much for your submission! Very happy to have you present at the next Meetup on August 17. I'll add you to the speaker line up.

**Comment by paulfioravanti** [comment]
Good luck at Elixir Conf, @mplatts! I'll close out this issue once the conference is over. Let me know if you don't want me to put the video up, and you'd rather have the Elixir Conf video end up being the "source of truth" for your talk.

**Comment by paulfioravanti** [comment]
Hi @mplatts, now that [ElixirConf has put your talk up](https://www.youtube.com/watch?v=GgEQJXfsI58), do you have any particular opinions on what you'd like to do with the version you did for Elixir Sydney? Keep the ElixirConf one as the source of truth and the Elixir Sydney one as just a "live-only" version for people who came to the meetup? Release the Elixir Sydney version as well (either now, or some time later)?

I'm happy with whatever you're happy with. If you think ElixirConf's version best serves your talk, and you don't want to cannibalise views from there, then that's all good with me, and the Elixir Australia version does not need to go live. Let me know what you think :)

**Comment by paulfioravanti** [comment]
Actually, I think the videos from that meetup may be lost... so, let's just keep this version of your talk as meetup-specific, and we can all enjoy the ElixirConf version.

**Comment by mplatts** [comment]
No worries
