### ISSUE TITLE
Wordle: Learning by Building

### ISSUE THREAD

**Issue by Theosaurus-Rex** [elixirsydney/elixirsydney#66]
**Brief summary of the talk content**
How does a beginner learn a new language? By building a project from the ground up! Theo talks about how his onboarding as a technical consultant at Alembic involved picking apart and reconstructing the popular browser-based language game Wordle.
(This is a practice run Josh asked me to do before Colorado 😅)

**Which month's meetup you would like to present at**
August 2022

 **Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)**
Around 25min max

**Your Twitter username (if you have one)**
@dino_coder

**Comment by paulfioravanti** [comment]
Nice. If you would like, we can hold off on putting the video of this talk out until after the ElixirConf version is done, or just not release it at all and just leave it as a "live only" version of the talk.

**Comment by paulfioravanti** [comment]
Seems that the videos from the August meetup have been lost, which is a bit of a bummer, but given that it covers the ground of a [video already up](https://www.youtube.com/watch?v=OIOlNr7LRz4) on the channel that you did before, and I'm sure that ElixirConf will get around to putting the actual conference video up eventually, your talk itself has not been lost.
