### ISSUE TITLE
Hooked on ContentEditable in LiveView with Surface

### ISSUE THREAD

**Issue by mbuhot** [elixirsydney/elixirsydney#67]
In this talk I'll show how to create simple editable and live updating HTML using contenteditable, LiveView Hooks and Surface.

- Which month's meetup you would like to present at: September 2022
- Length of talk: 20 mins
- Your Twitter username: @MikeBuhot
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: https://user-images.githubusercontent.com/336840/84208720-b7789b00-aaf7-11ea-8464-26a62b2bac65.png

**Comment by mbuhot** [comment]
slides: https://docs.google.com/presentation/d/1A4Efo4mv9uCdTywSrcUDBSDEbra0sxeJ8ZlpoUeSTY8/

**Comment by paulfioravanti** [comment]
Thanks, @mbuhot! [Video link](https://www.youtube.com/watch?v=SnFl3R0UccE).
