### ISSUE TITLE
Playdate - Making multiplayer games with the STAPLE stack

### ISSUE THREAD

**Issue by mbuhot** [elixirsydney/elixirsydney#68]
- Brief summary of the talk content: How we use interactive web games to demonstrate the flexibility and power of the STAPLE stack.
- Which month's meetup you would like to present at: September 2022
- Length of talk: 20 mins
- Your Twitter username: N/A.
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: ![59449](https://user-images.githubusercontent.com/59449/190932240-c177f591-5a0e-411b-89fe-3cc83fc9c72d.jpg)

**Comment by paulfioravanti** [comment]
Thanks, @jimsynz! [Video link](https://www.youtube.com/watch?v=xe9QeG4_cJo).
