### ISSUE TITLE
ElixirConf 2022 Wrap Up

### ISSUE THREAD

**Issue by Theosaurus-Rex** [elixirsydney/elixirsydney#69]
## Brief summary of the talk content
Theo will go over the highlights from this year's ElixirConf in Colorado, including exciting new features coming to Elixir and Phoenix!
## Which month's meetup you would like to present at
September 2022
## Length of talk
15 min
## Your Twitter username (if you have one)
@dino_coder

Just use my noggin from GitHub please :)

**Comment by paulfioravanti** [comment]
Thanks, @Theosaurus-Rex! [Video link](https://www.youtube.com/watch?v=yTx4g93RVGg).
