### ISSUE TITLE
The Erlang SSH library

### ISSUE THREAD

**Issue by ausimian** [elixirsydney/elixirsydney#70]
Learn how to do cool things with the ssh library that ships with the erlang standard libraries. The talk will cover clients and servers including shells and subsystems.

October, in-person

**Comment by paulfioravanti** [comment]
Awesome, @ausimian! You're scheduled up!

**Comment by paulfioravanti** [comment]
By the way, @ausimian, is this you? https://www.linkedin.com/in/nick-gunn/

**Comment by ausimian** [comment]
Maybe it could be someone squatting, I thought I fully deleted my acct a few years back. can you send me a screenshot?

**Comment by paulfioravanti** [comment]
It might be some other Nick Gunn. Basically, I want more information about you, like photo for promotional purposes. I can see that your Twitter is https://twitter.com/ausimian

**Comment by ausimian** [comment]
From a bio perspective, I’ve worked at Microsoft where I was a Senior Engineer in Robotics Research and then a Principal Engineer on HoloLens. After leaving Microsoft I worked at Optiver for a while, before joining Linchpin Labs. Since July this year I’ve been doing Elixir full time (amongst other things) at another security related startup.

**Comment by paulfioravanti** [comment]
Thanks! Got a photo of you I can use?

**Comment by ausimian** [comment]
Nope. You can use my GitHub avatar tho.

**Comment by paulfioravanti** [comment]
Thanks very much @ausimian! Your video is [here](https://www.youtube.com/watch?v=13uVIwynIXw).
