### ISSUE TITLE
I learned Gleam in a week - here's how it went

### ISSUE THREAD

**Issue by Theosaurus-Rex** [elixirsydney/elixirsydney#71]
## Summary
When a friend and fellow Elixir enthusiast dragged me into the Gleam community discord server, I found a tight-knit community who were passionate about their language. I decided to learn Gleam in the span of a week and share my experience with other devs who also have an Elixir background. Do I have any idea what I'm doing? Come join us and find out!

## Deets
Aiming to give this talk in-person at October's meetup. Will be shooting for around 25-30 minutes but knowing me it will probably end up being slightly shorter when I inevitably talk at a million miles per hour. 

@dino_coder on twitter as always 🦖

**Comment by paulfioravanti** [comment]
Thanks, @Theosaurus-Rex! You're on for October!

**Comment by paulfioravanti** [comment]
Great job, @Theosaurus-Rex! Your video is [here](https://www.youtube.com/watch?v=-8OIK4RIUsg).
