### ISSUE TITLE
Lightning Talk - Was this a terrible terrible idea? 

### ISSUE THREAD

**Issue by Yasmin-A95** [elixirsydney/elixirsydney#72]
Thanks for proposing a lightning talk for Elixir Sydney!

Please provide the following information:

- Name of talk (in the title field)
Was this a terrible terrible idea?
- Brief summary of the talk content
Yasmin considers whether it was a terrible mistake to quit her job and enroll in a three month software engineering immersive. 
- Which month's meetup you would like to present at
The upcoming Elixir meetup
- Will the talk be given in-person or online
In person
- Your Twitter username (if you have one)
@Yasmin_Arch
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck (if you don't specify one, we'll see if we can find one from your social media accounts)
Either of the following depending on whether my cat isn't professional enough looking. 
<img width="554" alt="MeandBoo" src="https://user-images.githubusercontent.com/107013100/195226395-f5be1e02-5c4d-4ddf-bf21-54f5c82862b2.PNG">
<img width="478" alt="Me and Art pic" src="https://user-images.githubusercontent.com/107013100/195226429-7eee8a64-2896-42b6-9e4e-91956e11264f.png">

**Comment by paulfioravanti** [comment]
Thanks, @Yasmin-A95! You're on for Oct 19!

**Comment by paulfioravanti** [comment]
Thanks so much @Yasmin-A95! Your video is [here](https://www.youtube.com/watch?v=R8tWN2rwT88).
