### ISSUE TITLE
Postgres triggers -> PubSub -> LiveView

### ISSUE THREAD

**Issue by suranyami** [elixirsydney/elixirsydney#74]
Dynamically create and remove Postgres triggers to monitor changes to items of interest for a user in a LiveView dashboard. The example we'll work through simulates some crypto exchange prices.

Meetup: 16 November 2022
In-Person presentation
Length: 15 minutes? Depends how much I waffle on
Twitter: social media is a cancer consuming the heart of civil society

![krishna_small](https://user-images.githubusercontent.com/69984/200107062-839f54c7-e65f-472b-b95b-0c55db443bbd.png)

**Comment by paulfioravanti** [comment]
Locked in for November 16! Thanks, @suranyami!
