### ISSUE TITLE
Nerves Ecosystem State - Tools and basics

### ISSUE THREAD

**Issue by phonnz** [elixirsydney/elixirsydney#77]
- A walk through the basics of Nerves in the current ecosystem, tooling, and a powerful zip of tips for beginners who want to start building or learn about IoT Elixir ecosystem capabilities. 
 (Toolshed, custom_system, cross-compiling, livebook, phx,  monitoring) 
- February
- online
- 25 minutes
- phonnz.dev | @phonnz
- https://phonnz.dev/img/phonnz.jpg

**Comment by paulfioravanti** [comment]
Great to have you back, @phonnz! You're on for the February 15, 2023 meetup!

**Comment by paulfioravanti** [comment]
This can wait here till you're ready to try again :)

**Comment by phonnz** [comment]
So sorry for not  being available the last time, I am ready if there's a chance for March 15 :)

**Comment by joshprice** [comment]
That would be fantastic @phonnz consider yourself locked in!

**Comment by paulfioravanti** [comment]
Thanks @phonnz! Here's your video: https://youtu.be/NveitdplX6o
