### ISSUE TITLE
Vixen - An Implementation of the Noise Protocol Framework for the BEAM

### ISSUE THREAD

**Issue by ausimian** [elixirsydney/elixirsydney#78]
[Vixen](https://github.com/ausimian/vixen) is a library implementing the [Noise Protocol Framework](https://noiseprotocol.org/). The talk will cover the framework, as well as the design and implementation of the library.

- Which month's meetup you would like to present at
Feb or March

- Will the talk be given in-person or online
In person

- Length of talk (Max 30 minutes, but feel free to take less time; the more succinct, the better!)
20-30 mins

- Where you can be found on the internet (e.g. personal website, social media account links etc)
twitter.com/ausimian

- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck
https://avatars.githubusercontent.com/u/15211687?s=80&v=4

**Comment by paulfioravanti** [comment]
Let's go full speed ahead for the February 15 Meetup. Thanks, @ausimian!

**Comment by paulfioravanti** [comment]
Thanks, @ausimian! Your video is here: https://www.youtube.com/watch?v=ngzrlEuDBHk
