### ISSUE TITLE
Building Better Elixir Applications with the Ash Framework

### ISSUE THREAD

**Issue by joshprice** [elixirsydney/elixirsydney#79]
The Ash framework has been around for a while now but has been rapidly gaining developer attention since it's 2.0 release last year. In this lightning talk I'll try to demystify what Ash is, what it's goals are and how it can help you build ambitious Elixir applications with more confidence.

- 15 March
- In person

**Comment by paulfioravanti** [comment]
Thanks @joshprice! Here's your video: https://youtu.be/duSq-lKMCqs
