### ISSUE TITLE
Getting embedded with Nerves

### ISSUE THREAD

**Issue by fimac** [elixirsydney/elixirsydney#8]
A talk on how to get started with embedded software using Nerves.

**Comment by paulfioravanti** [comment]
Awesome, thanks @fimac ! You're on for next week!

**Comment by paulfioravanti** [comment]
Thanks for doing your Nerves talk, Fiona! If you wanted to share your slide deck, or any other materials, please tweet them out to `@ElixirSydney` and we'll give it a retweet.
