### ISSUE TITLE
Why I built Ash Authentication.

### ISSUE THREAD

**Issue by jimsynz** [elixirsydney/elixirsydney#80]
Recently I released the first public version of the `ash_authentication` package, which makes user authentication a first-class citizen inside the Ash ecosystem.  This talk is about why I built it and a short demonstration of how to use it.

March 15th
Remote

**Comment by paulfioravanti** [comment]
Thanks @jimsynz! Here's your video: https://www.youtube.com/watch?v=QkKY0YJcRDg
