### ISSUE TITLE
Exercism: Nucleotide Count

### ISSUE THREAD

**Issue by ClementineOldfield** [elixirsydney/elixirsydney#9]
Given a single stranded DNA string, compute how many times each nucleotide occurs in the string.

The genetic language of every living thing on the planet is DNA. DNA is a large molecule that is built from an extremely long sequence of individual elements called nucleotides. 4 types exist in DNA and these differ only slightly and can be represented as the following symbols: 'A' for adenine, 'C' for cytosine, 'G' for guanine, and 'T' thymine.

Here is an analogy:

twigs are to birds nests as
nucleotides are to DNA as
legos are to lego houses as
words are to sentences as...

**Comment by paulfioravanti** [comment]
Thanks for doing your lightning talk, Clem! If you want to share anything, like, say, a link to your solution, either on Exercism or a Gist or whatever, please tweet it out to `@ElixirSydney` and we'll give it a retweet.
